mlm/apps/authentication/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from .views import (
    ProfileCreateView,
    ProfileDetailView,
    ProfileUpdateView,
    ActivateAccountView,
    AccountActivationSent,
    RegistrationView,
)

app_name = "authentication"
urlpatterns = [
    # User
    path(
        "", auth_views.LoginView.as_view(redirect_authenticated_user=True), name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", RegistrationView.as_view(), name="register"),
    # Email Confirm
    path(
        "account_activation_sent/",
        AccountActivationSent.as_view(),
        name="account_activation_sent",
    ),
    re_path(
        r"^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        ActivateAccountView.as_view(),
        name="activate-account",
    ),
    # Password Reset
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    # Password Change
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # Profile
    path("profile/create/", ProfileCreateView.as_view(), name="profile-create"),
    path("profile/<int:pk>/", ProfileDetailView.as_view(), name="profile-detail"),
    path(
        "profile/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile-update"
    ),
]

mlm/apps/main/urls.py
from django.urls import path, include

from .views import index, mlm_views, admin_views

app_name = "main"

admin_patterns = [
    path(
        "clients/list/",
        admin_views.MLMClientListView.as_view(),
        name="admin-clients-list",
    ),
    path(
        "client/<int:pk>/update/",
        admin_views.MLMClientUpdateView.as_view(),
        name="admin-client-update",
    ),
    path(
        "client/create/",
        admin_views.AdminRegistrationView.as_view(),
        name="admin-client-create",
    ),
    path("config/", admin_views.MLMConfigView.as_view(), name="admin-config"),
    path(
        "client/activation/<int:type_>/<int:pk>/",
        admin_views.MLMClientDeactivateView.as_view(),
        name="admin-client-activation",
    ),
    path(
        "client/add/",
        admin_views.AdminRegistrationView.as_view(),
        name="admin-client-add",
    ),
]


urlpatterns = [
    path("dashboard/", index.DashboardView.as_view(), name="dashboard"),
    path("no-client/", index.NoClientView.as_view(), name="no-client-redirect"),
    path("tree/", mlm_views.ClientDescendantTreeView.as_view(), name="tree"),
    path("balance/", mlm_views.ClientBalanceView.as_view(), name="balance"),
    path(
        "transactions/",
        mlm_views.TransactionsStatementListView.as_view(),
        name="statement",
    ),
    # ADMIN VIEWS
    path("mlmadmin/", include(admin_patterns)),
]

mlm/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings

from django.contrib.auth import views as auth_views

urlpatterns = [
    path("yandani/", admin.site.urls),
    path("", include("mlm.apps.main.urls", namespace="main")),
    path("", include("mlm.apps.authentication.urls", namespace="auth")),
    # Other AUth_Views
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    re_path(
        r"reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mlm/apps/core/models.py
from django.db import models
from django.utils import timezone


class TimestampedModel(models.Model):
    # A timestamp representing when this object was created.
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    # A timestamp reprensenting when this object was last updated.
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    # updated_by = models.ForeignKey("human_resources.Operator", null=True, blank=True)
    # created_by = models.ForeignKey("human_resources.Operator", null=True, blank=True)

    class Meta:
        abstract = True

        # By default, any model that inherits from `TimestampedModel` should
        # be ordered in reverse-chronological order. We can override this on a
        # per-model basis as needed, but reverse-chronological is a good
        # default ordering for most models.
        ordering = ["-created_at", "-updated_at"]

mlm/apps/authentication/forms.py
import unicodedata

from django import forms
from django.contrib.auth import authenticate, get_user_model, password_validation
from django.contrib.auth.hashers import UNUSABLE_PASSWORD_PREFIX, identify_hasher
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.text import capfirst
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _

from .models import User, Profile

UserModel = get_user_model()


class UsernameField(forms.CharField):
    def to_python(self, value):
        return unicodedata.normalize("NFKC", super().to_python(value))


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """

    error_messages = {"password_mismatch": _("The two password fields didn't match.")}
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = UserModel
        fields = ("username", "email")
        field_classes = {"username": UsernameField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs.update(
                {"autofocus": True}
            )
        if self._meta.model.USERNAME_FIELD != "email":
            self.fields["email"] = forms.EmailField(label=_("E-mail"), max_length=75)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages["password_mismatch"], code="password_mismatch"
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get("password2")
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except forms.ValidationError as error:
                self.add_error("password2", error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class AdminProfileCreationForm(forms.ModelForm):
    email = forms.EmailField()
    username = forms.CharField(max_length=150)
    parent = forms.CharField(max_length=20, label=_("Upline ID"))

    class Meta:
        model = Profile
        exclude = ("user",)

mlm/apps/main/forms.py
from django import forms
from .models import MLMConfig


class MLMConfigForm(forms.ModelForm):
    class Meta:
        model = MLMConfig
        fields = "__all__"

mlm/apps/authentication/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.contrib.auth import get_user_model, login

from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.utils.encoding import force_text

from django.conf import settings

from braces.views import FormValidMessageMixin, FormInvalidMessageMixin

from mlm.apps.main import settings as mlm_settings

from .models import Profile
from .forms import UserCreationForm
from .tokens import account_activation_token

User = get_user_model()


class ProfileCreateView(
    LoginRequiredMixin, FormValidMessageMixin, FormInvalidMessageMixin, CreateView
):
    template_name = "auth/profile_form.html"
    model = Profile
    fields = ["first_name", "middle_name", "last_name", "avatar", "about_me"]
    form_valid_message = "Profile created successfully."
    form_invalid_message = "Profile not created."

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        obj = form.save(commit=False)

        if not self.request.user.mlm_clients.exists():
            parent_client_id = self.request.POST.get("mlmparent", None)

            if parent_client_id is None:
                messages.error(self.request, "L'ID du parent absent.")
                return super(ProfileCreateView, self).form_invalid(form)
            else:
                from mlm.apps.main.models import MLMClient  # isort:skip
                from mlm.apps.main.utils.base import create_client

                try:
                    parent_client = MLMClient.objects.get(client_id=parent_client_id)
                except MLMClient.DoesNotExist:
                    messages.error(self.request, "L'ID du parrain invalide.")
                    return super(ProfileCreateView, self).form_invalid(form)

                if (
                    parent_client.get_children().count()
                    >= mlm_settings.MAX_AFFILIATION_NUMBER
                ):
                    messages.error(
                        self.request,
                        "L'upline a atteint le nombre maximal de parrainages.",
                    )
                    return super(ProfileCreateView, self).form_invalid(form)

                create_client(self.request.user, parent=parent_client)

        obj.user = self.request.user
        self.object = obj.save()

        return super(ProfileCreateView, self).form_valid(form)

    def form_invalid(self, form):
        # print(form.errors)
        return super(ProfileCreateView, self).form_invalid(form)


class ProfileUpdateView(
    LoginRequiredMixin, FormValidMessageMixin, FormInvalidMessageMixin, UpdateView
):
    template_name = "auth/profile_form.html"
    model = Profile
    fields = ["first_name", "middle_name", "last_name", "avatar", "about_me"]
    form_valid_message = "Profile updated successfully."
    form_invalid_message = "Profile not updated."


class ProfileDetailView(LoginRequiredMixin, DetailView):
    template_name = "auth/profile_detail.html"
    model = Profile


class RegistrationView(FormView):
    form_class = UserCreationForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("main:dashboard")

    def form_valid(self, form):
        user = form.save(commit=False)

        # Force Mail COnfirm ?
        if getattr(settings, "FORCE_MAIL_CONFIRM", True):
            user.is_active = False
        user.save()
        current_site = get_current_site(self.request)
        subject = "Activation de votre compte"
        message = render_to_string(
            "email/account_activation_email.html",
            {
                "user": user,
                "domain": current_site.domain,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": account_activation_token.make_token(user),
            },
        )
        user.email_user(subject, message)
        return redirect("auth:account_activation_sent")
        # return super().form_valid(form)


class ActivateAccountView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.email_confirmed = True
            user.save()
            login(self.request, user)
            return redirect(getattr(settings, "LOGIN_REDIRECT_URL", "/"))
        else:
            return render(request, "registration/account_activation_invalid.html")


class AccountActivationSent(View):
    def get(self, request):
        return render(request, "registration/account_activation_sent.html")

mlm/apps/main/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin


class DashboardView(LoginRequiredMixin, View):
    template_name = "main/dashboard.html"

    def get(self, request):
        return render(self.request, self.template_name, locals())

mlm/apps/main/views/index.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class DashboardView(LoginRequiredMixin, View):
    template_name = "main/dashboard.html"

    def get(self, request):
        return render(self.request, self.template_name, locals())


class NoClientView(LoginRequiredMixin, TemplateView):
    template_name = "main/no_client.html"

mlm/apps/main/views/mixins.py
from django.contrib.auth.mixins import LoginRequiredMixin


class MLMAdminRequiredMixin(LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or not request.user.is_mlm_staff:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

mlm/apps/main/views/mlm_views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _

from mlm.apps.main.models import MLMClient, MLMTransaction


class ClientDescendantTreeView(LoginRequiredMixin, View):
    template_name = "mlm/desc_tree.html"

    def get(self, request):
        page_title = _("Affiliations")
        return render(self.request, self.template_name, locals())


class TransactionsStatementListView(LoginRequiredMixin, ListView):
    template_name = "mlm/statement.html"
    model = MLMTransaction

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(client__user__pk=self.request.user.pk)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["page_title"] = _("Historique des Transactions")

        return context


class ClientBalanceView(LoginRequiredMixin, View):
    template_name = "mlm/balance.html"

    def get(self, request):
        page_title = _("Solde")
        return render(self.request, self.template_name, locals())

mlm/apps/main/templates/mlm/admin/mlm_clients_list.html
{% extends "base.html" %}
{% load i18n humanize static %}

{% block header %}
{% if user.mlmclient.is_valid %}
<!-- Header -->
<div class="container-fluid">
  <div class="header-body">
    <!-- Card stats -->
    <div class="row">
      <div class="col text-light">
        Voici une liste des clients.
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock header %}

{% block content %}
<!-- Table -->
<div class="row">
  <div class="col">
    <div class="card shadow">
      <div class="card-header border-0 clearfix">
        <h3 class="mb-0 float-left">{% trans 'Clients' %}</h3>
        <a href="{% url 'main:admin-client-add' %}" class="btn btn-sm btn-primary float-right">
          <i class="fas fa-plus"></i> {% trans 'Nouveau' %}
        </a>
      </div>
      <div class="table-responsive">
        <table class="table align-items-center table-flush">
          <thead class="thead-light">
            <tr>
              <th scope="col">{% trans 'Noms' %}</th>
              <th scope="col">{% trans 'ID' %}</th>
              <th scope="col">{% trans 'Upline' %}</th>
              <th scope="col">{% trans 'Affiliations' %}</th>
              <th scope="col">{% trans 'Admin' %}</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for client in object_list %}
            <tr>
              <td>
                {% if client.is_active %}
                <span class="badge badge-dot mr-4" title="{% trans 'Actif' %}">
                  <i class="bg-success"></i>
                </span>
                {% else %}
                <span class="badge badge-dot mr-4" title="{% trans 'Inactif' %}">
                  <i class="bg-danger"></i>
                </span>
                {% endif %}
                {{ client.user.get_full_name }}
                {% if client.user.get_full_name != client.user.username %}<b>({{ client.user.username }})</b>{% endif %}
              </td>
              <td>
                <span title="{{ client.client_id }}">{{ client.client_id }}</span>
              </td>
              <td>
                <span title="{{ client.parent.user.get_full_name }} ({{ client.client_id }})">
                  {{ client.parent.user.get_full_name }}
                  <b>({{ client.parent.client_id }})</b>
                </span>
              </td>
              <td>
                {{ client.affiliations.count|intcomma }}
              </td>
              <td>
                {% if client.user.is_mlm_staff %}
                <span class="badge badge-dot mr-4" title="{% trans 'Admin' %}">
                  <i class="bg-success"></i>
                </span>
                {% else %}
                <span class="badge badge-dot mr-4" title="{% trans 'Normal' %}">
                  <i class="bg-danger"></i>
                </span>
                {% endif %}
              </td>
              <td class="text-right">
                <div class="dropdown">
                  <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                    <a class="dropdown-item" href="{{ client.get_absolute_url }}">Details</a>
                    {% if client.is_active %}
                    <a class="dropdown-item" href="{{ client.get_deactivation_url }}">Désactiver</a>
                    {% else %}
                    <a class="dropdown-item" href="{{ client.get_activation_url }}">Activer</a>
                    {% endif %}
                    {% if not client.user.is_mlm_staff %}
                    <a class="dropdown-item" href="{{ client.get_set_admin_url }}">Nommer Admin</a>
                    {% else %}
                    <a class="dropdown-item" href="{{ client.get_delete_admin_url }}">Retirer Admin</a>
                    {% endif %}
                  </div>
                </div>
              </td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="6">{% trans 'Pas de transaction ...' %}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="card-footer py-4">
        <nav aria-label="...">
          <ul class="pagination justify-content-end mb-0">
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1">
                <i class="fas fa-angle-left"></i>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            <li class="page-item active">
              <a class="page-link" href="#">1 <span class="sr-only">(current)</span></a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">2</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
              <a class="page-link" href="#">
                <i class="fas fa-angle-right"></i>
                <span class="sr-only">Next</span>
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

mlm/apps/main/templates/mlm/admin/mlm_config.html
{% extends 'base.html' %}
{% load i18n static %}

{% block content %}
<div class="row">
  <div class="col">
    <div class="card shadow border-0">
      <div class="card-header bg-white border-0">
        <div class="row align-items-center">
          <div class="col-8">
            <h3 class="mb-0">{% trans "Configuration" %}</h3>
          </div>
          <div class="col-4 text-right">
            <a href="{{ user.get_profile_url }}" class="btn btn-sm btn-primary">{% trans 'Profile' %}</a>
          </div>
        </div>
      </div>
      <div class="card-body">
        <form method="post" action="">
          {% csrf_token %}
          {% include "libs/bs4_form.html" with form=form %}
          <button type="submit" class="btn btn-info">{% trans "Save changes" %}</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

mlm/apps/main/templates/mlm/admin/user_registration.html
{% extends "base.html" %}
{% load i18n widget_tweaks %}

{% block content %}
<div class="row">
        <div class="col-xl-12 mb-5 mb-xl-0">
          <div class="card shadow">
            <div class="card-header bg-transparent">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">{% trans 'Création Compte Client' %}</h3>
                </div>
                <div class="col-4 text-right">
                  <a href="#!" class="btn btn-sm btn-primary">Param&egrave;tres</a>
                </div>
              </div>
            </div>
            <div class="card-body">
              <form role="form" method="post" action="" enctype="mulipart/form-data">
                {% csrf_token %}
                {% include "libs/bs4_form_head.html" with form=form %}
                  <h6 class="heading-small text-muted mb-4">Utilisateur</h6>
                  <div class="pl-lg-4">
                    <div class="row">
                      <div class="col-lg-4">
                        <div class="form-group">
                          <label class="form-control-label" for="">{{ form.username.label }}</label>
                        <!-- {% render_field form.username placeholder=form.username.label class="form-control form-control-alternative" %} -->

                        {% include "libs/bs4_field_essential.html" with field=form.username placeholder=form.username.label %}
                        </div>
                      </div>
                      <div class="col-lg-4">
                        <div class="form-group">
                          <label class="form-control-label" for="">{{ form.email.label }}</label>
                        <!-- {% render_field form.email placeholder=form.email.label class="form-control form-control-alternative" %} -->

                        {% include "libs/bs4_field_essential.html" with field=form.email placeholder=form.email.label %}
                        </div>
                      </div>
                      <div class="col-lg-4">
                        <div class="form-group">
                          <label class="form-control-label" for="">{{ form.parent.label }}</label>
                        <!-- {% render_field form.parent placeholder=form.parent.label class="form-control form-control-alternative" %} -->

                        {% include "libs/bs4_field_essential.html" with field=form.parent placeholder=form.parent.label %}
                        </div>
                      </div>
                    </div>
                  </div>
                <h6 class="heading-small text-muted mb-4">Informations personnelles</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="">{{ form.first_name.label }}</label>
                        <!-- {% render_field form.first_name placeholder=form.first_name.label class="form-control form-control-alternative" %} -->

                        {% include "libs/bs4_field_essential.html" with field=form.first_name placeholder=form.first_name.label %}
                      </div>
                    </div>

                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="">{{ form.middle_name.label }}</label>
                        <!-- {% render_field form.middle_name placeholder=form.middle_name.label class="form-control form-control-alternative" %} -->
                        {% include "libs/bs4_field_essential.html" with field=form.middle_name placeholder=form.middle_name.label %}
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="input-last-name">{{ form.last_name.label }}</label>
                        <!-- {% render_field form.last_name placeholder=form.last_name.label class="form-control form-control-alternative" %} -->
                        {% include "libs/bs4_field_essential.html" with field=form.last_name placeholder=form.last_name.label %}
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="input-last-name">{{ form.avatar.label }}</label>
                        <!-- {% render_field form.avatar placeholder=form.avatar.label class="custom-file" %} -->
                        {% include "libs/bs4_field_essential.html" with field=form.avatar placeholder=form.avatar.label %}
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="my-4" />
                <!-- Address -->
                <!-- <h6 class="heading-small text-muted mb-4">Contact information</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-address">Address</label>
                        <input id="input-address" class="form-control form-control-alternative" placeholder="Home Address" value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09" type="text">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="input-city">City</label>
                        <input type="text" id="input-city" class="form-control form-control-alternative" placeholder="City" value="New York">
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Country</label>
                        <input type="text" id="input-country" class="form-control form-control-alternative" placeholder="Country" value="United States">
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Postal code</label>
                        <input type="number" id="input-postal-code" class="form-control form-control-alternative" placeholder="Postal code">
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="my-4" /> -->
                <!-- Description -->
                <h6 class="heading-small text-muted mb-4">Bio</h6>
                <div class="pl-lg-4">
                  <div class="form-group">
                    <label>A propos de moi</label>
                    <!-- <textarea rows="4" class="form-control form-control-alternative" placeholder="A few words about you ...">A beautiful Dashboard for Bootstrap 4. It is Free and Open Source.</textarea> -->
                    <!-- {% render_field form.about_me rows="4" class="form-control form-control-alternative" placeholder="Quelques mots parlant de toi ..." %} -->
                    {% include "libs/bs4_field_essential.html" with field=form.about_me placeholder=form.about_me.label %}
                  </div>
                </div>
                <div class="text-right">
                  <button class="btn btn-primary" type="submit">Enregistrer</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}