mlm/apps/authentication/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from .views import (
    ProfileCreateView,
    ProfileDetailView,
    ProfileUpdateView,
    ActivateAccountView,
    AccountActivationSent,
    RegistrationView,
)

app_name = "authentication"
urlpatterns = [
    # User
    path(
        "", auth_views.LoginView.as_view(redirect_authenticated_user=True), name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", RegistrationView.as_view(), name="register"),
    # Email Confirm
    path(
        "account_activation_sent/",
        AccountActivationSent.as_view(),
        name="account_activation_sent",
    ),
    re_path(
        r"^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        ActivateAccountView.as_view(),
        name="activate-account",
    ),
    # Password Reset
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    # Password Change
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # Profile
    path("profile/create/", ProfileCreateView.as_view(), name="profile-create"),
    path("profile/<int:pk>/", ProfileDetailView.as_view(), name="profile-detail"),
    path(
        "profile/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile-update"
    ),
]

mlm/apps/main/urls.py
from django.urls import path, include

from .views import index, mlm_views, admin_views

app_name = "main"

admin_patterns = [
    path(
        "clients/list/",
        admin_views.MLMClientListView.as_view(),
        name="admin-clients-list",
    ),
    path(
        "client/<int:pk>/update/",
        admin_views.MLMClientUpdateView.as_view(),
        name="admin-client-update",
    ),
    path(
        "client/create/",
        admin_views.AdminRegistrationView.as_view(),
        name="admin-client-create",
    ),
    path("config/", admin_views.MLMConfigView.as_view(), name="admin-config"),
    path(
        "client/activation/<int:type_>/<int:pk>/",
        admin_views.MLMClientDeactivateView.as_view(),
        name="admin-client-activation",
    ),
    path(
        "client/add/",
        admin_views.AdminRegistrationView.as_view(),
        name="admin-client-add",
    ),
]


urlpatterns = [
    path("dashboard/", index.DashboardView.as_view(), name="dashboard"),
    path("no-client/", index.NoClientView.as_view(), name="no-client-redirect"),
    path("tree/", mlm_views.ClientDescendantTreeView.as_view(), name="tree"),
    path("balance/", mlm_views.ClientBalanceView.as_view(), name="balance"),
    path(
        "transactions/",
        mlm_views.TransactionsStatementListView.as_view(),
        name="statement",
    ),
    # ADMIN VIEWS
    path("mlmadmin/", include(admin_patterns)),
]

mlm/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings

from django.contrib.auth import views as auth_views

urlpatterns = [
    path("yandani/", admin.site.urls),
    path("", include("mlm.apps.main.urls", namespace="main")),
    path("", include("mlm.apps.authentication.urls", namespace="auth")),
    # Other AUth_Views
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    re_path(
        r"reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mlm/apps/core/models.py
from django.db import models
from django.utils import timezone


class TimestampedModel(models.Model):
    # A timestamp representing when this object was created.
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    # A timestamp reprensenting when this object was last updated.
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    # updated_by = models.ForeignKey("human_resources.Operator", null=True, blank=True)
    # created_by = models.ForeignKey("human_resources.Operator", null=True, blank=True)

    class Meta:
        abstract = True

        # By default, any model that inherits from `TimestampedModel` should
        # be ordered in reverse-chronological order. We can override this on a
        # per-model basis as needed, but reverse-chronological is a good
        # default ordering for most models.
        ordering = ["-created_at", "-updated_at"]

mlm/apps/authentication/forms.py
import unicodedata

from django import forms
from django.contrib.auth import authenticate, get_user_model, password_validation
from django.contrib.auth.hashers import UNUSABLE_PASSWORD_PREFIX, identify_hasher
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.text import capfirst
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _

from .models import User, Profile

UserModel = get_user_model()


class UsernameField(forms.CharField):
    def to_python(self, value):
        return unicodedata.normalize("NFKC", super().to_python(value))


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """

    error_messages = {"password_mismatch": _("The two password fields didn't match.")}
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = UserModel
        fields = ("username", "email")
        field_classes = {"username": UsernameField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs.update(
                {"autofocus": True}
            )
        if self._meta.model.USERNAME_FIELD != "email":
            self.fields["email"] = forms.EmailField(label=_("E-mail"), max_length=75)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages["password_mismatch"], code="password_mismatch"
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get("password2")
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except forms.ValidationError as error:
                self.add_error("password2", error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class AdminProfileCreationForm(forms.ModelForm):
    email = forms.EmailField()
    username = forms.CharField(max_length=150)
    parent = forms.CharField(max_length=20, label=_("Upline ID"))

    class Meta:
        model = Profile
        exclude = ("user",)

mlm/apps/main/forms.py
from django import forms
from .models import MLMConfig


class MLMConfigForm(forms.ModelForm):
    class Meta:
        model = MLMConfig
        fields = "__all__"

mlm/apps/authentication/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.contrib.auth import get_user_model, login

from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.utils.encoding import force_text

from django.conf import settings

from braces.views import FormValidMessageMixin, FormInvalidMessageMixin

from mlm.apps.main import settings as mlm_settings

from .models import Profile
from .forms import UserCreationForm
from .tokens import account_activation_token

User = get_user_model()


class ProfileCreateView(
    LoginRequiredMixin, FormValidMessageMixin, FormInvalidMessageMixin, CreateView
):
    template_name = "auth/profile_form.html"
    model = Profile
    fields = ["first_name", "middle_name", "last_name", "avatar", "about_me"]
    form_valid_message = "Profile created successfully."
    form_invalid_message = "Profile not created."

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        obj = form.save(commit=False)

        if not self.request.user.mlm_clients.exists():
            parent_client_id = self.request.POST.get("mlmparent", None)

            if parent_client_id is None:
                messages.error(self.request, "L'ID du parent absent.")
                return super(ProfileCreateView, self).form_invalid(form)
            else:
                from mlm.apps.main.models import MLMClient  # isort:skip
                from mlm.apps.main.utils.base import create_client

                try:
                    parent_client = MLMClient.objects.get(client_id=parent_client_id)
                except MLMClient.DoesNotExist:
                    messages.error(self.request, "L'ID du parrain invalide.")
                    return super(ProfileCreateView, self).form_invalid(form)

                if (
                    parent_client.get_children().count()
                    >= mlm_settings.MAX_AFFILIATION_NUMBER
                ):
                    messages.error(
                        self.request,
                        "L'upline a atteint le nombre maximal de parrainages.",
                    )
                    return super(ProfileCreateView, self).form_invalid(form)

                create_client(self.request.user, parent=parent_client)

        obj.user = self.request.user
        self.object = obj.save()

        return super(ProfileCreateView, self).form_valid(form)

    def form_invalid(self, form):
        # print(form.errors)
        return super(ProfileCreateView, self).form_invalid(form)


class ProfileUpdateView(
    LoginRequiredMixin, FormValidMessageMixin, FormInvalidMessageMixin, UpdateView
):
    template_name = "auth/profile_form.html"
    model = Profile
    fields = ["first_name", "middle_name", "last_name", "avatar", "about_me"]
    form_valid_message = "Profile updated successfully."
    form_invalid_message = "Profile not updated."


class ProfileDetailView(LoginRequiredMixin, DetailView):
    template_name = "auth/profile_detail.html"
    model = Profile


class RegistrationView(FormView):
    form_class = UserCreationForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("main:dashboard")

    def form_valid(self, form):
        user = form.save(commit=False)

        # Force Mail COnfirm ?
        if getattr(settings, "FORCE_MAIL_CONFIRM", True):
            user.is_active = False
        user.save()
        current_site = get_current_site(self.request)
        subject = "Activation de votre compte"
        message = render_to_string(
            "email/account_activation_email.html",
            {
                "user": user,
                "domain": current_site.domain,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": account_activation_token.make_token(user),
            },
        )
        user.email_user(subject, message)
        return redirect("auth:account_activation_sent")
        # return super().form_valid(form)


class ActivateAccountView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.email_confirmed = True
            user.save()
            login(self.request, user)
            return redirect(getattr(settings, "LOGIN_REDIRECT_URL", "/"))
        else:
            return render(request, "registration/account_activation_invalid.html")


class AccountActivationSent(View):
    def get(self, request):
        return render(request, "registration/account_activation_sent.html")

mlm/apps/main/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin


class DashboardView(LoginRequiredMixin, View):
    template_name = "main/dashboard.html"

    def get(self, request):
        return render(self.request, self.template_name, locals())

mlm/apps/main/views/index.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class DashboardView(LoginRequiredMixin, View):
    template_name = "main/dashboard.html"

    def get(self, request):
        return render(self.request, self.template_name, locals())


class NoClientView(LoginRequiredMixin, TemplateView):
    template_name = "main/no_client.html"

mlm/apps/main/views/mixins.py
from django.contrib.auth.mixins import LoginRequiredMixin


class MLMAdminRequiredMixin(LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or not request.user.is_mlm_staff:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

mlm/apps/main/views/mlm_views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _

from mlm.apps.main.models import MLMClient, MLMTransaction


class ClientDescendantTreeView(LoginRequiredMixin, View):
    template_name = "mlm/desc_tree.html"

    def get(self, request):
        page_title = _("Affiliations")
        return render(self.request, self.template_name, locals())


class TransactionsStatementListView(LoginRequiredMixin, ListView):
    template_name = "mlm/statement.html"
    model = MLMTransaction

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(client__user__pk=self.request.user.pk)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["page_title"] = _("Historique des Transactions")

        return context


class ClientBalanceView(LoginRequiredMixin, View):
    template_name = "mlm/balance.html"

    def get(self, request):
        page_title = _("Solde")
        return render(self.request, self.template_name, locals())

mlm/templates/inc/aside.html
{% load static i18n %}

<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Brand -->
      <a class="navbar-brand pt-0" href="{% url 'main:dashboard' %}">
        <!-- <img src="{% static 'img/brand/blue.png' %}" class="navbar-brand-img" alt="..."> -->
        <span class="mlm_brand text-primary">{{ MLM_GROUP_NAME }}</span>
      </a>
      <!-- User -->
      <!-- <ul class="nav align-items-center d-md-none">
        <li class="nav-item dropdown">
          <a class="nav-link nav-link-icon" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-bell-55"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right" aria-labelledby="navbar-default_dropdown_1">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="{% static 'img/theme/team-1-800x800.jpg' %}
">
              </span>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
            <div class=" dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-settings-gear-65"></i>
              <span>Settings</span>
            </a>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-calendar-grid-58"></i>
              <span>Activity</span>
            </a>
            <a href="./examples/profile.html" class="dropdown-item">
              <i class="ni ni-support-16"></i>
              <span>Support</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="#!" class="dropdown-item">
              <i class="ni ni-user-run"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul> -->
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Collapse header -->
        <div class="navbar-collapse-header d-md-none">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="{% url 'main:dashboard' %}">
                <!-- <img src="{% static 'img/brand/blue.png' %}"> -->
                <span class="mlm_brand text-primary">{{ MLM_GROUP_NAME }}</span>
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>

        {% if user.mlm_clients.all.exists %}
        <!-- Form -->
        <form class="mt-4 mb-3 d-md-none">
          <div class="input-group input-group-rounded input-group-merge">
            <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Search" aria-label="Search">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <span class="fa fa-search"></span>
              </div>
            </div>
          </div>
        </form>
        <!-- Navigation -->
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link active" href="{% url 'main:dashboard' %}"> <i class="ni ni-tv-2 text-primary"></i> Tableau de bord
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'main:tree' %}">
              <i class="ni ni-bullet-list-67 text-blue"></i> Descendants
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <i class="ni ni-circle-08 text-primary"></i> Transactions
            </a>
            <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
              <div class=" dropdown-header noti-title">
                <h6 class="text-overflow m-0">Transactions!</h6>
              </div>
              <a href="{% url 'main:statement' %}" class="dropdown-item">
                <i class="ni ni-fat-delete"></i>
                <span>{% trans 'Historique' %}</span>
              </a>
              <a href="{% url 'main:balance' %}" class="dropdown-item">
                <i class="ni ni-fat-delete"></i>
                <span>{% trans 'Solde' %}</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item">
                <i class="ni ni-fat-delete"></i>
                <span>{% trans 'Transfert' %}</span>
              </a>
              <a href="#" class="dropdown-item">
                <i class="ni ni-fat-delete"></i>
                <span>{% trans 'Retrait' %}</span>
              </a>
            </div>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link " href="./examples/maps.html">
              <i class="ni ni-pin-3 text-orange"></i> Maps
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="./examples/profile.html">
              <i class="ni ni-single-02 text-yellow"></i> User profile
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="./examples/tables.html">
              <i class="ni ni-bullet-list-67 text-red"></i> Tables
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="./examples/login.html">
              <i class="ni ni-key-25 text-info"></i> Login
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="./examples/register.html">
              <i class="ni ni-circle-08 text-pink"></i> Register
            </a>
          </li>-->
        </ul>
        {% endif %}
        {% if user.is_mlm_staff %}
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        <h6 class="navbar-heading text-muted">{% trans 'Gestion' %}</h6>
        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:admin-clients-list' %}">
              <i class="ni ni-map-big"></i> {% trans 'Clients' %}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:admin-config' %}">
              <i class="ni ni-map-big"></i> {% trans 'Configurations' %}
            </a>
          </li>
        </ul>
        {% endif %}
        {% if user.is_staff %}
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        <h6 class="navbar-heading text-muted">{% trans 'Administration' %}</h6>
        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">
              <i class="ni ni-spaceship"></i> {% trans 'Accueil' %}
            </a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/foundation/colors.html">
              <i class="ni ni-palette"></i> Foundation
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/components/alerts.html">
              <i class="ni ni-ui-04"></i> Components
            </a>
          </li> -->
        </ul>
        {% endif %}
      </div>
    </div>
  </nav>

mlm/templates/inc/footer.html
<!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
              &copy; {% now "Y" %} <a href="!#" class="font-weight-bold ml-1" target="_blank">{{ MLM_GROUP_NAME }}</a>
              <i>v{{ MLM_VERSION }}</i>
            </div>
          </div>
          <div class="col-xl-6">
            <ul class="nav nav-footer justify-content-center justify-content-xl-end">
              {% if user.mlm_clients.all.exists %}
              <li class="nav-item">
                <a href="{% url 'main:dashboard' %}" class="nav-link">Dashboard</a>
              </li>
              <li class="nav-item">
                <a href="{{ user.get_profile_url }}" class="nav-link">Profile</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a href="{% url 'auth:logout' %}" class="nav-link">Logout</a>
              </li>
              <!-- <li class="nav-item">
                <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
              </li> -->
            </ul>
          </div>
        </div>
      </footer>

mlm/templates/inc/navbar.html
{% load static i18n %}
<!-- Navbar -->
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
  <div class="container-fluid">
    <!-- Brand -->
    <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="{% url 'main:dashboard' %}">{{ page_title|default:"Tableau de bord" }}</a>
    <!-- Form -->
    <form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
      <div class="form-group mb-0">
        <div class="input-group input-group-alternative">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-search"></i></span>
          </div>
          <input class="form-control" placeholder="Search" type="text">
        </div>
      </div>
    </form>
    <!-- User -->
    <ul class="navbar-nav align-items-center d-none d-md-flex">
      <li class="nav-item dropdown">
        <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="media align-items-center">
            <span class="avatar avatar-sm rounded-circle">
              <img alt="Image placeholder" src="{% if user.profile.avatar %}{{ user.profile.avatar.url }}{% else%}{% static 'img/default-user.png' %}{% endif %}">
            </span>
            <div class="media-body ml-2 d-none d-lg-block">
              <span class="mb-0 text-sm  font-weight-bold">{{ user.get_full_name }}</span>
            </div>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
          <div class=" dropdown-header noti-title">
            <h6 class="text-overflow m-0">Bienvenue!</h6>
          </div>
          {% if user.mlm_clients.all.exists %}
          <a href="{{ user.get_profile_url }}" class="dropdown-item">
            <i class="ni ni-single-02"></i>
            <span>Profil</span>
          </a>
          <a href="{% url 'auth:password_change' %}" class="dropdown-item">
            <i class="ni ni-key-25"></i>
            <span>{% trans 'Changer Mot de Passe' %}</span>
          </a>
          <a href="{{ user.get_profile_url }}" class="dropdown-item">
            <i class="ni ni-settings-gear-65"></i>
            <span>Param&egrave;tres</span>
          </a>
          {% endif %}
          <!-- <a href="{{ user.get_profile_url }}" class="dropdown-item">
            <i class="ni ni-calendar-grid-58"></i>
            <span>Activity</span>
          </a>
          <a href="{{ user.get_profile_url }}" class="dropdown-item">
            <i class="ni ni-support-16"></i>
            <span>Support</span>
          </a> -->
          <div class="dropdown-divider"></div>
          <a href="{% url 'auth:logout' %}" class="dropdown-item">
            <i class="ni ni-user-run"></i>
            <span>Logout</span>
          </a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<!-- End Navbar -->